// import React from 'react';
import { AppLogo } from "./image/svgIcons/IcAppLogo";
import { BackArrow } from "./image/svgIcons/IcBackArrow";
import { BarCode } from "./image/svgIcons/IcBarCode";
import { Chat } from "./image/svgIcons/IcChat";
import { Check } from "./image/svgIcons/IcCheck";
import { CommonPoint } from "./image/svgIcons/IcCommonPoint";
import { DotsVertical } from "./image/svgIcons/IcDotsVertical";
import { Home } from "./image/svgIcons/IcHome";
import { Language } from "./image/svgIcons/IcLanguage";
import { LeftArrow } from "./image/svgIcons/IcLeftArrow";
import { Logout } from "./image/svgIcons/IcLogout";
import { MenuBar } from "./image/svgIcons/IcMenuBar";
import { MotorBike } from "./image/svgIcons/IcMotorBike";
import { ParcelBox } from "./image/svgIcons/IcParcelBox";
import { Person } from "./image/svgIcons/IcPerson";
import { Plus } from "./image/svgIcons/IcPlus";
import { Profile } from "./image/svgIcons/IcProfile";
import { Question } from "./image/svgIcons/IcQuestion";
import { RightAroow } from "./image/svgIcons/IcRightArrow";
import { Route } from "./image/svgIcons/IcRoute";
import { Scanner } from "./image/svgIcons/IcScanner";
import { Search } from "./image/svgIcons/IcSearch";
import { Thailand } from "./image/svgIcons/IcThailand";
import { UK } from "./image/svgIcons/IcUK";
import { Wallet } from "./image/svgIcons/IcWallet";

export const IcAppLogo = props => <AppLogo {...props} />;
export const IcMenuBar = props => <MenuBar {...props} />;
export const IcPerson = props => <Person {...props} />;
export const IcPlus = props => <Plus {...props} />;
export const IcHome = props => <Home {...props} />;
export const IcWallet = props => <Wallet {...props} />;
export const IcRoute = props => <Route {...props} />;
export const IcChat = props => <Chat {...props} />;
export const IcProfile = props => <Profile {...props} />;
export const IcBackArrow = props => <BackArrow {...props} />;
export const IcLanguage = props => <Language {...props} />;
export const IcThailand = props => <Thailand {...props} />;
export const IcUK = props => <UK {...props} />;
export const IcCheck = props => <Check {...props} />;
export const IcSearch = props => <Search {...props} />;
export const IcBarCode = props => <BarCode {...props} />;
export const IcLogout = props => <Logout {...props} />;
export const IcParcelBox = props => <ParcelBox {...props} />;
export const IcScanner = props => <Scanner {...props} />;
export const IcRightArrow = props => <RightAroow {...props} />;
export const IcLeftArrow = props => <LeftArrow {...props} />;
export const IcCommonPont = props => <CommonPoint {...props} />;
export const IcDotsVertical = props => <DotsVertical {...props} />;
export const IcQuestion = props => <Question {...props} />;
export const IcMotorBike = props => <MotorBike {...props} />;