export const ADD_RIDER = 'ADD_RIDER';
export const LOGOUT_USER = 'LOGOUT_USER'


export const SET_LOCATION_PERMISSION = 'SET_LOCATION_PERMISSION';
export const CURRENT_USER = 'CURRENT_USER';

export const DELIVERY_STATUS_CODE = 'DELIVERY_STATUS_CODE';
export const TRACKING_KEY = 'TRACKING_KEY'